### ISSUE TITLE
Reacts to titles with batteries in them:

### ISSUE THREAD

**Issue by thorleifjaocbsen** [notoriousbdg/Home-AssistantConfig#1]
Neo CoolCam Battery Powered PIR Sensor Luminance (22.0)

This shows up when i set my "Max" over 22. Seems like it reacts to "Battery" in the name of the node?

**Comment by notoriousbdg** [comment]
Sorry for the delay.  Not sure how I missed this.  That is because Battery is in the name.  You can make the package ignore it by adding a flag to customize like this:

```yaml
homeassistant:
  customize:
    sensor.sensor_with_battery_attibute:
      battery_sensor_creation_disabled: true
```
