### ISSUE TITLE
Battery Level unknown

### ISSUE THREAD

**Issue by phdelodder** [notoriousbdg/Home-AssistantConfig#3]
I have a device using zanzitto to publish the battery info, the device isn't often used resulting in a value 'unknown'. 

HA constantly shows Tablet Battery (Unknown), is there a way to filter out the 'unknown' value from the notification message?

**Comment by notoriousbdg** [comment]
To prevent that device from being included in alerts, you can add it to your customize section like this:
```yaml
homeassistant:
  customize:
    sensor.sensor_name_to_ignore_battery:
      battery_alert_disabled: true
```
